name: "Update Problems List"

on:
  push:
    branches: [master]

jobs:
  build:
    name: "Test action"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: ./actions
